wallpaper {
	monitor  = DP-2
	path     = ~/Pictures/Wallpapers/Ares/ares.jpg
	fit_mode = cover
}

wallpaper {
	monitor  = HDMI-A-1
	path     = ~/Pictures/Wallpapers/Ares/ares3.jpg
	fit_mode = cover
}

ipc = true
splash = false

